trigger:
  branches:
    include:
      - master
      - "*"

variables:
  poolName: $[iif(eq($(Build.SourceBranchName), 'master'), 'Azure Pipelines', 'Local Azure Agent')]

pool:
  name: $(poolName)

stages:
  - stage: Build
    displayName: "Build and Test"
    jobs:
      - job: Build
        displayName: "Restore, Build, and Test"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              version: "8.x"

          - script: dotnet restore "Local Azure Devops Agent.sln"
            displayName: "Restore dependencies"

          - script: dotnet build "Local Azure Devops Agent.sln" --no-restore --configuration Release
            displayName: "Build"

  - stage: PlantUMLDiagramGeneration
    displayName: "Generate PlantUML Diagram"
    jobs:
      - job: GenerateDiagram
        displayName: "Run PlantUML Docker to generate image"
        steps:
          - download: current

          - task: Bash@3
            displayName: "Generate PNG from PlantUML"
            env:
              POOL_NAME: $(poolName)
              MATCH_NAME: $(Build.SourceBranchName)
              PLANTUML_JAR: $(Build.SourcesDirectory)/plantuml.jar
              WORKSPACE_DIR: "$(Build.SourcesDirectory)/Local Azure Devops Agent/Assets"
              OUTPUT_DIR: $(Build.SourcesDirectory)/attachments
            inputs:
              targetType: "filePath"
              filePath: docker-scripts/devops/generate_plantuml.sh

          - publish: $(Build.SourcesDirectory)/attachments/umbraco-models.png
            artifact: plantuml-image
